# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports =
		[ (modulesPath + "/installer/scan/not-detected.nix")
		];

	boot={
		initrd.availableKernelModules = [ 
		"xhci_pci" "thunderbolt" 
		"nvme" "usbhid" "usb_storage" 
		"sd_mod" "sdhci_pci" 
		];
		initrd.kernelModules = [ ];
		kernelModules = [ "kvm-intel" ];
		extraModulePackages = [ ];
	};

	fileSystems = {
		"boot/efi" = {
			device = "/dev/disk/by-uuid/FED5-34ED";
			fsType = "vfat";
			options = [
				"umask=0077"
				"fmask=0022"
				"dmask=0022"
			];
		};
		"/" = {
			device = "/dev/disk/by-uuid/ea5a05c7-0aac-4a8f-9544-88bf8ba2fa33";
			fsType = "btrfs";
			options = [
				"compress=zstd"
				"noatime"
				"subvol=@nixos"
			];
		};
		"/home/unsafe" = {
			device = "/dev/disk/by-uuid/ea5a05c7-0aac-4a8f-9544-88bf8ba2fa33";
			fsType = "btrfs";
			options = [
				"compress=zstd"
				"noatime"
				"subvol=@VM"
			];
		};
		"/home/VMS" = {
			device = "/dev/disk/by-uuid/a2a06942-a7ba-40a6-acf9-c2811caff238";
			fsType = "xfs";
			options = [
				"noatime"
			];
		};
	};


	swapDevices = [ ];

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

	hardware.bluetooth.enable = true;
}

