# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports =
		[ (modulesPath + "/installer/scan/not-detected.nix")
		];

	boot={
		kernelPackages = pkgs.stable.linuxPackages_zen;
		supportedFilesystems = [ "ntfs" ];
		kernel.sysctl = {
			"kernel.perf_event_paranoid" = 0;
		};
		kernelParams=[
			"intel_iommu=on"
			"iommu=pt"
			"i915.force_probe=!a7a0"
			"xe.force_probe=a7a0"
		];
		initrd.availableKernelModules = [
		"xhci_pci" "thunderbolt"
		"nvme" "usbhid" "usb_storage"
		"sd_mod" "sdhci_pci"
		];
		initrd.kernelModules = [ ];
		kernelModules = [ "kvm-intel" ];
		extraModulePackages = [ ];

		loader = {
			systemd-boot.enable = true;
			efi = {
				canTouchEfiVariables = true;
				efiSysMountPoint = "/boot/efi"; # ← use the same mount point here.
			};
			# grub = {
			# 	efiSupport = true;
			# 	#efiInstallAsRemovable = true; # 如果 canTouchEfiVariables不能用
			# 	device = "nodev";
			# };
		};
	};

	fileSystems = {
		"boot/efi" = {
			device = "/dev/disk/by-uuid/FED5-34ED";
			fsType = "vfat";
			options = [
				"umask=0077"
				"fmask=0022"
				"dmask=0022"
			];
		};
		"/" = {
			device = "/dev/disk/by-uuid/ea5a05c7-0aac-4a8f-9544-88bf8ba2fa33";
			fsType = "btrfs";
			options = [
				"compress=zstd"
				"noatime"
				"subvol=@nixos"
			];
		};
		"/home/unsafe" = {
			device = "/dev/disk/by-uuid/ea5a05c7-0aac-4a8f-9544-88bf8ba2fa33";
			fsType = "btrfs";
			options = [
				"compress=zstd"
				"noatime"
				"subvol=@VM"
			];
		};
		"/home/VMS" = {
			device = "/dev/disk/by-uuid/a2a06942-a7ba-40a6-acf9-c2811caff238";
			fsType = "xfs";
			options = [
				"noatime"
			];
		};
	};


	swapDevices = [ ];

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

	hardware.bluetooth.enable = true;

	# 显卡驱动
	hardware.graphics = {
		enable = true;
		# 如果你是 32 位应用兼容需求，可以开启
		# enable32Bit = true;
		# 安装对应显卡的 VAAPI 驱动
		extraPackages = with pkgs; [
			# Intel
			intel-media-driver
			# intel-vaapi-driver # 适用于较旧的 CPU
			# AMD
			# amdvlk
			# 通用/其他
			# libvdpau-va-gl
		];
	};
}
