model_list:
    - model_name: deepseek-reasoner
      litellm_params:
          model: deepseek/deepseek-reasoner
          api_key: os.environ/DEEPSEEK_API_KEY
          api_base: https://api.deepseek.com

    - model_name: deepseek-chat
      litellm_params:
          model: deepseek/deepseek-chat
          api_key: os.environ/DEEPSEEK_API_KEY
          api_base: https://api.deepseek.com

    - model_name: minimax-m2.7
      litellm_params:
          model: minimax/MiniMax-M2.7
          api_key: os.environ/MINIMAX_API_KEY
          api_base: https://api.minimaxi.com/anthropic

    - model_name: minimax-m2.7-highspeed
      litellm_params:
          model: minimax/MiniMax-M2.7-highspeed
          api_key: os.environ/MINIMAX_API_KEY
          api_base: https://api.minimaxi.com/anthropic

litellm_settings:
    drop_params: true
    modify_params: true
