[bar.default]
center = [ "taskbar" ]
end = [ "group:g4", "group:g1", "volume", "group:g3", "control-center" ]
margin_edge = 0
margin_ends = 0
padding = 1
radius = 0
shadow = false
start = [ "group:g2", "clock", "wallpaper", "media" ]

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g1"
    members = [ "network", "bluetooth" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g2"
    members = [ "cpu", "ram" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g3"
    members = [ "brightness", "battery" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g4"
    members = [ "tray", "clipboard" ]
    opacity = 1.0
    padding = 6.0

[desktop_widgets]
enabled = false
schema_version = 1
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[shell]
font_family = "Maple Mono NF CN"
ui_scale = 1.1000000089406967

    [shell.panel]
    open_near_click_control_center = true
    shadow = false

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "2"
    variant = "destructive"

    [[shell.session.actions]]
    action = "suspend"
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "4"
    variant = "destructive"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "5"
    variant = "destructive"

    [[shell.session.actions]]
    action = "command"
    command = "systemctl hibernate"
    enabled = true
    glyph = "hibernate"
    label = "hibernate"
    variant = "secondary"

[theme]
builtin = "Catppuccin"

[wallpaper]
directory = "/home/e/.local/share/wallpapers"

    [wallpaper.default]
    path = "/home/e/.local/share/wallpapers/plasma/ScarletTree/contents/images_dark/wallhaven_mpy829.jpg"

    [wallpaper.last]
    path = "/home/e/.local/share/wallpapers/plasma/ScarletTree/contents/images_dark/wallhaven_mpy829.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/e/.local/share/wallpapers/plasma/ScarletTree/contents/images_dark/wallhaven_mpy829.jpg"

[widget.clock]
capsule = true
format = "{:%m-%d %H:%M %a}"

[widget.control-center]
capsule = true
glyph = "disabled-2"

[widget.media]
capsule = true
max_length = 91

[widget.network]
show_label = false

[widget.taskbar]
group_by_workspace = true
hide_empty_workspaces = true
inactive_opacity = 0.82999999999999996
scale = 1.2
workspace_label_placement = "centered"

[widget.tray]
capsule = true
scale = 1.25

[widget.volume]
capsule = true
scroll_step = 1

[widget.wallpaper]
capsule = true
